export const demoVenues = [
  {
    googlePlaceId: "DEMO_paris_08_loft_etoile",
    name: "Demo Loft Etoile",
    venueType: "Loft",
    address: "12 rue fictive de l'Etoile, 75008 Paris",
    city: "Paris",
    arrondissement: "8e",
    zone: "Paris 8e",
    phone: "+33 1 00 00 08 12",
    website: "https://example.com/demo-loft-etoile",
    mapsUrl: "https://maps.google.com/?q=Demo%20Loft%20Etoile",
    photos: ["https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.7,
    reviewCount: 128,
    capacity: 180,
    privateHire: "Oui",
    kactusStatus: "Absent de Kactus",
    source: "Mode demonstration - donnees fictives",
    commercial: {
      responsible: "Steven",
      status: "A contacter",
      contacted: "Non",
      interested: "A verifier",
      comment: "Lieu demo prioritaire pour cocktail corporate.",
      nextFollowUpDate: new Date().toISOString().slice(0, 10)
    }
  },
  {
    googlePlaceId: "DEMO_boulogne_rooftop_seine",
    name: "Demo Rooftop Seine",
    venueType: "Rooftop",
    address: "4 quai imaginaire, 92100 Boulogne-Billancourt",
    city: "Boulogne-Billancourt",
    arrondissement: "",
    zone: "Boulogne-Billancourt",
    phone: "+33 1 00 00 92 10",
    website: "https://example.com/demo-rooftop-seine",
    mapsUrl: "https://maps.google.com/?q=Demo%20Rooftop%20Seine",
    photos: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.4,
    reviewCount: 76,
    capacity: 90,
    privateHire: "A verifier",
    kactusStatus: "Presence incertaine",
    source: "Mode demonstration - donnees fictives",
    commercial: {
      responsible: "Gabriel",
      status: "A verifier",
      contacted: "Non",
      interested: "A verifier",
      comment: "Verifier l'offre entreprise et la capacite assise.",
      nextFollowUpDate: ""
    }
  },
  {
    googlePlaceId: "DEMO_paris_11_theatre_bleu",
    name: "Demo Theatre Bleu",
    venueType: "Theatre",
    address: "27 passage fictif, 75011 Paris",
    city: "Paris",
    arrondissement: "11e",
    zone: "Paris 11e",
    phone: "+33 1 00 00 11 27",
    website: "https://example.com/demo-theatre-bleu",
    mapsUrl: "https://maps.google.com/?q=Demo%20Theatre%20Bleu",
    photos: ["https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.8,
    reviewCount: 312,
    capacity: 320,
    privateHire: "Oui",
    kactusStatus: "Present sur Kactus",
    source: "Mode demonstration - donnees fictives",
    commercial: {
      responsible: "Steven",
      status: "Present sur Kactus",
      contacted: "Oui",
      interested: "Non",
      comment: "Masque par defaut car detecte Kactus.",
      nextFollowUpDate: ""
    }
  },
  {
    googlePlaceId: "DEMO_paris_02_galerie_lumiere",
    name: "Demo Galerie Lumiere",
    venueType: "Galerie",
    address: "9 rue exemple, 75002 Paris",
    city: "Paris",
    arrondissement: "2e",
    zone: "Paris 2e",
    phone: "",
    website: "https://example.com/demo-galerie-lumiere",
    mapsUrl: "https://maps.google.com/?q=Demo%20Galerie%20Lumiere",
    photos: ["https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1200&q=80"],
    rating: 4.5,
    reviewCount: 51,
    capacity: 120,
    privateHire: "Oui",
    kactusStatus: "Absent de Kactus",
    source: "Mode demonstration - donnees fictives",
    commercial: {
      responsible: "Gabriel",
      status: "Nouveau",
      contacted: "Non",
      interested: "A verifier",
      comment: "Ajouter email direct apres verification du site officiel.",
      nextFollowUpDate: ""
    }
  }
];
