create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null unique,
  role text not null default 'Prospection'
);

create table if not exists public.venues (
  id bigint generated by default as identity primary key,
  google_place_id text unique,
  name text not null,
  normalized_name text not null,
  venue_type text,
  address text,
  normalized_address text,
  city text,
  arrondissement text,
  zone text,
  phone text,
  normalized_phone text,
  website text,
  maps_url text,
  photos_json text not null default '[]',
  rating numeric,
  review_count integer,
  capacity integer,
  private_hire text not null default 'A verifier',
  kactus_status text not null default 'Presence incertaine',
  kactus_verified_at timestamptz,
  kactus_verification_method text not null default '',
  kactus_result_url text not null default '',
  kactus_result_summary text not null default '',
  kactus_validated_by text not null default '',
  kactus_validated_at timestamptz,
  last_checked_at timestamptz,
  source text not null default 'A verifier',
  sync_status text not null default 'Nouveau',
  is_demo boolean not null default false,
  already_done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_venues_place_id on public.venues (google_place_id);
create index if not exists idx_venues_lookup on public.venues (normalized_name, normalized_address, normalized_phone);
create index if not exists idx_venues_filters on public.venues (city, arrondissement, venue_type, kactus_status, sync_status);

create table if not exists public.commercial_data (
  venue_id bigint primary key references public.venues(id) on delete cascade,
  contacted text not null default 'Non',
  responsible text not null default 'Steven',
  interested text not null default 'A verifier',
  comment text not null default '',
  contact_name text not null default '',
  contact_role text not null default '',
  direct_email text not null default '',
  contact_method text not null default 'Telephone',
  first_contact_date text not null default '',
  last_contact_date text not null default '',
  next_follow_up_date text not null default '',
  status text not null default 'Nouveau',
  updated_at timestamptz not null default now()
);

create index if not exists idx_commercial_status on public.commercial_data (status, responsible, contacted, interested, next_follow_up_date);

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  venue_id bigint not null references public.venues(id) on delete cascade,
  user_name text not null,
  action_type text not null,
  comment text not null default '',
  status_change text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  mode text not null,
  new_count integer not null default 0,
  updated_count integer not null default 0,
  verify_count integer not null default 0,
  kactus_count integer not null default 0,
  commercial_overwrite_count integer not null default 0,
  message text not null default ''
);

create table if not exists public.sync_progress (
  id integer primary key check (id = 1),
  current_step_index integer not null default 0,
  pending_json text not null default '[]',
  pending_index integer not null default 0,
  total_steps integer not null default 0,
  total_found integer not null default 0,
  added_count integer not null default 0,
  duplicate_count integer not null default 0,
  last_completed_step text not null default '',
  last_endpoint text not null default '',
  initial_completed boolean not null default false,
  last_sync_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.sync_step_status (
  step_key text primary key,
  zone text not null,
  category text not null,
  status text not null default 'A faire',
  found_count integer not null default 0,
  added_count integer not null default 0,
  duplicate_count integer not null default 0,
  endpoint text not null default '',
  error text not null default '',
  updated_at timestamptz not null default now()
);

insert into public.users (name)
values ('Steven'), ('Gabriel')
on conflict (name) do nothing;

insert into public.sync_progress (id)
values (1)
on conflict (id) do nothing;

alter table public.users enable row level security;
alter table public.venues enable row level security;
alter table public.commercial_data enable row level security;
alter table public.history enable row level security;
alter table public.sync_runs enable row level security;
alter table public.sync_progress enable row level security;
alter table public.sync_step_status enable row level security;
